#!/bin/bash

# See LICENSE file for copyright and license details.

SESSNAME=${1:-${USER}}

[ -f ${HOME}/.bashrc ] && . ${HOME}/.bashrc

[ -n "${TMUX}" ] && exit 0

JUNKID=999999999
THOME="${HOME}/.tmux"
TBIN="tmux -S ${THOME}/socket"
TSESSION="${THOME}/${SESSNAME}.session"
if [ ! -r ${TSESSION} ]; then
	TSESSION="${THOME}/default.session"
fi

SESSNAME=${SESSNAME:0:8}

if [ -z "$(${TBIN} list-sessions|grep ${SESSNAME})" ]; then
	if [ -r ${TSESSION} ]; then
		${TBIN} new-session -d -n DeF -s ${SESSNAME} ${SHELL}
		${TBIN} select-window -t 0
		${TBIN} move-window -t:${JUNKID}
		cat ${TSESSION} | while read CURLINE ; do
			[ -n "${CURLINE}" ] && echo ${CURLINE} |xargs ${TBIN}
		done
		${TBIN} kill-window -t:${JUNKID}
	else
		${TBIN} new-session -d -s ${SESSNAME}
	fi
fi

exec ${TBIN} attach -t ${SESSNAME}